filter:
    excluded_paths: [node_modules/*, .github/*]

build:
    nodes:
        analysis:
            tests:
                environment:
                    node: v18.12.1
                override:
                    - js-scrutinizer-run